spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
logging:
  level:
    root: INFO
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    # Включает информацию о сборке (spring-boot-maven-plugin)
    build:
      enabled: true
    # Включает информацию о приложении из application.yml
    git:
      mode: "full"

# Собственно, сама информация
info:
  app:
    # Пример фильтрации свойств Maven
    version: @project.version@
    author: Andrey
    description: Andrey do it