spring:
  main:
    allow-circular-references: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 0
      database: SpringBatchExampleDB

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat

